log:
  level: "DEBUG"
  time: "24h"
  count: 200
tasks:
  - name: "任务1"
    workdir: "/datadisk/adp/logs"
    corn: "0 * * * * ?"
    #清理符合类型的  1 文件 2目录 3递归目录文件 4递归目录文件清理空目录
    filter-type: 4
    #清理符合正则表达式的文件或目录
    filter-regex: ".+\\.log"
    #排除文件 排除优先与 上面的规则
    excludes-regex:
    #最少保留最近几个文件
    clean-keep: 10
    #最少保留最近几天的文件
    time-offset: "240h"
    #最大处理文件数，超出后将在下次任务处理
    max-batch: 200
  - name: "样例任务"
    #要清理的日志或备份文件所在目录
    workdir: "/datadisk/testdata2"
    #定时执行清理任务
    corn: "0 * * * * ?"
    #清理符合类型的 1 文件 2目录 3递归目录文件 4递归目录文件清理空目录
    filter-type: 1
    #清理符合正则表达式的文件或目录
    filter-regex: ".+\\.txt"
    #排除文件 排除优先与 上面的规则
    excludes-regex:
      - ".+副本 +4.+\\.txt"
      - ".+副本 +5.+\\.txt"
    #最少保留最近几个文件
    clean-keep: 3
    #最少保留最近几天的文件
    time-offset: "1h"
    #最大处理文件数，超出后将在下次任务处理
    max-batch: 200
    #测试模式不会删除文件
    test: true
